syn::custom_keyword!(vars);
syn::custom_keyword!(repeat);
syn::custom_keyword!(permeate);
syn::custom_keyword!(skip_repeat);
syn::custom_keyword!(stop_repeat);
syn::custom_keyword!(Unit);
syn::custom_keyword!(attribute);
syn::custom_keyword!(impl_attribute);
syn::custom_keyword!(inner_attribute);
